name: terminal.dart
version: 0.0.1
description: Linux Terminal Emulator
dependencies:
  browser: any
  sprintf: any
  ansicolor: ">=0.0.9 <0.1.0"
  quiver: '>=0.18.0<0.19.0'
dev_dependencies:
#  unittest: any
